server:
  port: 8080

auth-service:
  host: localhost
  port: 8081
  prefix: auth
flashcards-service:
  host: localhost
  port: 8082
  prefix: flashcards

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://${auth-service.host}:${auth-service.port}/
          predicates:
            - Path=/${auth-service.prefix}/**
        - id: flashcards
          uri: http://${flashcards-service.host}:${flashcards-service.port}/
          predicates:
            - Path=/${flashcards-service.prefix}/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /${auth-service.prefix}/v3/api-docs
        name: Authorization Service
      - url: /${flashcards-service.prefix}/v3/api-docs
        name: Flashcards Service